apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure-alerts.yaml
  - kubernetes-alerts.yaml
  - monitoring-alerts.yaml
  - flux-alerts.yaml
  - database-alerts.yaml
