apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: azure-devops

resources:
  - namespace.yaml
  - external-secret.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: azure-devops-agent
  app.kubernetes.io/part-of: ci-cd

commonAnnotations:
  managed-by: flux
